FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /server ./cmd/server

FROM alpine:latest

WORKDIR /app

COPY --from=builder /server .
COPY config.json .

RUN apk --no-cache add curl

EXPOSE 50051

CMD ["./server"]